### ISSUE TITLE
🍭 一些建议

### ISSUE THREAD

**Issue by visiky** [MrSmallLiu/G2Plot-Lollipop#1]
|||
|---|---|
|![image](https://user-images.githubusercontent.com/15646325/102705430-ce782100-42c2-11eb-83c7-e2f7d561d70e.png)|![image](https://user-images.githubusercontent.com/15646325/102706074-a9d37780-42c9-11eb-9615-ddba135ddddf.png)|

1. （✨）圆心对应具体数值的位置
2. 柱子穿过 point 其实还可以接受，一般来说 point 的颜色应该和柱子一致，且透明度应该不会比柱子高
3. （可选）是否可以翻转，参考：[vertical-lollipop-chart](https://www.highcharts.com/docs/chart-and-series-types/lollipop-series#vertical-lollipop-chart)  & [pizza demo](https://codesandbox.io/s/pizza-preference-rj18k?file=/index.js:2324-2489)
3. 柱子和 marker point 希望可以设置宽度和半径，默认可以取 point 半径为柱子宽度的一半的1.5倍（注意柱子高度小于宽度的情况）

另外，附加一个 [DEMO](https://codesandbox.io/s/bangbangtangtu-q3zlo?file=/src/index.js)

**Comment by MrSmallLiu** [comment]
1. 圆心对应数值最开始确实是的，但后来又考虑到特殊情况。现在还是应该改为圆心
2. 穿过point颜色无透明度或者圆小的时候看不出来，对于图表大一些，且有透明度情况，还是挺丑的

**Comment by MrSmallLiu** [comment]
3. 翻转暂时没有考虑做
4. 配置是继承于柱状图的了，然后把columnWidthRatio修改为了radiusRatio，暂时还没有写配置文档
